---
- name: Deploy web server
  hosts: web_servers
  become: true
  vars:
    package_name: nginx
    service_name: nginx
    deploy_status: "enabled"
    
  tasks:
    - name: install nginx
      apt:
        name: "{{ package_name }}"
        state: present
      
      
    - name: start nginx service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes
         
      when: deploy_status == "enabled"
